language: node_js
sudo: false
dist: trusty

node_js:
  #- "13.0"
  - "12.6"
  - "12.5"
  - "12.4"
  - "12.3"
  - "12.2"
  - "12.1"
  - "12.0"
  - "11.15"
  - "11.14"
  - "11.13"
  - "11.12"
  - "11.11"
  - "11.10"
  - "11.9"
  - "11.8"
  - "11.7"
  - "11.6"
  - "11.5"
  - "11.4"
  - "11.3"
  - "11.2"
  - "11.1"
  - "11.0"
  - 10

os: linux

stages:
  - check coding style
  - test
  - test with coverage

before_install:
  - stty cols 130

install:
  - travis_retry npm install

script: npm test

jobs:
  include:
    - stage: test with coverage
      node_js: "12.0"
      script: npm run test-and-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml

    - stage: check coding style
      node_js: "12.0"
      script: prettier -c "**/*.js"

notifications:
  email: false
