language: node_js
sudo: false
dist: trusty

node_js:
  - "10.0"
  - "9.11"
  - "9.10"
  - "9.9"
  - "9.8"
  - "9.7"
  - "9.6"
  - "9.5"
  - "9.4"
  - "9.3"
  - "9.2"
  - "9.1"
  - "9.0"
  - "8.9"
  - "8.8"
  - "8.7"
  - "8.6"
  - "8.5"
  - "8.4"
  - "8.3"
  - "8.2"
  - "8.1"
  - "8.0"
  - 7
  - 6

os: linux

stages:
  - test
  - test with coverage

before_install:
  - stty cols 130

script: "npm test"

jobs:
  fast_finish: true
  include:
    - stage: test with coverage
      node_js: "10.0"
      script: npm run test-and-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml
