version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:9.6
        environment:
          TZ: "/usr/share/zoneinfo/Europe/Berlin"
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "package.json" }}
            - composer-v1-
      - run: npm update
      - save_cache:
          key: composer-v1-{{ checksum "package.json" }}
          paths:
            - vendor
      - run: npm test

workflows:
  version: 2
  tests:
    jobs:
      - tests
